;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex3-3-1) (read-case-sensitive #t) (teachpacks ((lib "convert.rkt" "teachpack" "htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "convert.rkt" "teachpack" "htdp")) #f)))
(define (inches-cm inches)
  (* inches 2.54))
(define (feet-inches feet)
  (* feet 12))
(define (yards-feet yards)
  (* yards 3))
(define (rod-yards rod)
  (* rod (/ (+ (* 5 2) 1) 2)))
(define (furlongs-rods furlons)
  (* furlons 40))
(define (miles-furlongs miles)
  (* miles 8))

(inches-cm 1)
(inches-cm 2)
(inches-cm 3)
(feet-inches 1)
(feet-inches 2)
(feet-inches 3)
(yards-feet 1)
(yards-feet 2)
(yards-feet 3)
(rod-yards 1)
(rod-yards 2)
(rod-yards 3)
(furlongs-rods 1)
(furlongs-rods 2)
(furlongs-rods 3)
(miles-furlongs 1)
(miles-furlongs 2)
(miles-furlongs 3)